### ISSUE TITLE
Redundant boolean operations

### ISSUE THREAD

**Issue by abel1502** [cogu/cfile#3]
In several places I have found highly redundant boolean opertions. For example: https://github.com/cogu/cfile/blob/21bc32ba24a823d2d62c562ca48bb4d5878b8823/cfile/__init__.py#L25 can be rewritten as `self.sys=sys`, or `self.sys=bool(sys)` if you're paranoid about imprecise types. Also, in general, `x == True` is eqivalent to `x`, and `x == False` - to `not x`. I think refactoring this would make your code a lot clearer

**Comment by cogu** [comment]
The part of the code you mention was written more than 3 years ago. I agree that the cfile module as a whole needs refactoring.
